{% set name = "sec-edgar-mcp" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.13
    - pip
    - setuptools >=61.0
    - beautifulsoup4 >=4.12.0
  run:
    - python >=3.13
    - pip

test:
  imports:
    - sec_edgar_mcp

about:
  home: https://github.com/stefanoamorelli/sec-edgar-mcp
  summary: Open-source MCP server for the SEC EDGAR database
  description: |
    Provides access to SEC EDGAR database through a Model Context Protocol (MCP) server.
    Created by Stefano Amorelli.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefano.amorelli
